import { StyleSheet } from 'react-native';
import { GameColors } from './colors';
import { GAME_CONFIG } from './game';
import { scale, verticalScale, moderateScale, GROUND_HEIGHT, MODAL } from './layout';

export const gameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A2A4A',
  },
  skyLayer1: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '35%',
  },
  skyLayer2: {
    position: 'absolute',
    top: '20%',
    left: 0,
    right: 0,
    height: '40%',
    opacity: 0.85,
  },
  skyLayer3: {
    position: 'absolute',
    top: '50%',
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.7,
  },
  skyHorizonGlow: {
    position: 'absolute',
    bottom: GROUND_HEIGHT,
    left: 0,
    right: 0,
    height: verticalScale(160),
  },
  bgBuildingRow: {
    position: 'absolute',
    bottom: GROUND_HEIGHT,
    left: 0,
    right: 0,
    height: verticalScale(200),
  },
  bgBuilding: {
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: scale(4),
    borderTopRightRadius: scale(4),
  },
  gameWorld: {
    flex: 1,
  },
  touchArea: {
    flex: 1,
  },
  gameCloud: {
    position: 'absolute',
    width: scale(110),
    height: scale(50),
  },
  gcPart1: {
    position: 'absolute',
    width: scale(55),
    height: scale(32),
    borderRadius: scale(16),
    backgroundColor: 'rgba(255,255,255,0.85)',
    left: scale(5),
    top: scale(6),
  },
  gcPart2: {
    position: 'absolute',
    width: scale(70),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: 'rgba(255,255,255,0.85)',
    left: scale(18),
    top: scale(12),
  },
  obstacleGroup: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  obstacleTop: {
    position: 'absolute',
    top: 0,
    overflow: 'visible',
    borderRadius: scale(10),
    borderWidth: scale(3.5),
    borderColor: '#1A1A2E',
  },
  obstacleBottom: {
    position: 'absolute',
    overflow: 'visible',
    borderRadius: scale(10),
    borderWidth: scale(3.5),
    borderColor: '#1A1A2E',
  },
  pipeCap: {
    position: 'absolute',
    borderWidth: scale(3.5),
    borderRadius: scale(8),
    overflow: 'hidden',
    zIndex: 2,
  },
  character: {
    position: 'absolute',
    width: GAME_CONFIG.CHARACTER_SIZE + 14,
    height: GAME_CONFIG.CHARACTER_SIZE + 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailDot: {
    position: 'absolute',
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
    backgroundColor: 'rgba(255, 216, 74, 0.45)',
  },
  splatContainer: {
    position: 'absolute',
    width: scale(100),
    height: scale(100),
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  splatDot: {
    position: 'absolute',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  floatingScore: {
    position: 'absolute',
    zIndex: 60,
  },
  floatingScoreText: {
    fontSize: moderateScale(24),
    fontWeight: '900' as const,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 1.5,
  },
  groundStrip: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  groundGrass: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '56%',
    borderTopLeftRadius: scale(6),
    borderTopRightRadius: scale(6),
  },
  groundDirt: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '50%',
  },
  groundLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: scale(4),
    backgroundColor: '#1A1A2E',
  },
  hud: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    paddingHorizontal: scale(12),
  },
  hudRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hudPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(8, 8, 20, 0.72)',
    gap: scale(5),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 7,
  },
  hudPillText: {
    color: GameColors.uiWhite,
    fontSize: moderateScale(13),
    fontWeight: '700' as const,
  },
  hudCenter: {
    backgroundColor: 'rgba(8, 8, 20, 0.72)',
    minWidth: scale(85),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 7,
  },
  hudScore: {
    color: '#FFD84A',
    fontSize: moderateScale(28),
    fontWeight: '900' as const,
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 1.5,
  },
  hudLevelDot: {
    paddingHorizontal: scale(7),
    paddingVertical: verticalScale(2),
    borderRadius: scale(8),
    marginTop: verticalScale(2),
  },
  hudLevelText: {
    fontSize: moderateScale(8),
    fontWeight: '900' as const,
    color: GameColors.uiWhite,
    letterSpacing: 0.5,
  },
  readyOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  readyCard: {
    backgroundColor: 'rgba(10, 10, 25, 0.78)',
    paddingHorizontal: scale(44),
    paddingVertical: verticalScale(26),
    borderRadius: scale(24),
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 28,
    elevation: 14,
  },
  readyText: {
    fontSize: moderateScale(32),
    fontWeight: '900' as const,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.55)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 3,
  },
  readySubtext: {
    fontSize: moderateScale(13),
    fontWeight: '600' as const,
    color: 'rgba(255,255,255,0.6)',
    marginTop: verticalScale(6),
  },
  pauseOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 10, 25, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 200,
  },
  pauseCard: {
    backgroundColor: 'rgba(255,254,248,0.98)',
    borderRadius: scale(28),
    padding: scale(28),
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.6)',
    shadowColor: 'rgba(0,0,0,0.45)',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 1,
    shadowRadius: 40,
    elevation: 22,
    overflow: 'hidden',
  },
  pauseCardGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: scale(3),
    backgroundColor: '#FFD84A',
    opacity: 0.8,
  },
  pauseTitle: {
    fontSize: moderateScale(28),
    fontWeight: '900' as const,
    color: '#1A1A2E',
    marginBottom: verticalScale(20),
    letterSpacing: 4,
    textShadowColor: 'rgba(0,0,0,0.06)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  pauseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6AB832',
    paddingHorizontal: scale(28),
    paddingVertical: verticalScale(15),
    borderRadius: scale(16),
    gap: scale(10),
    borderWidth: 0,
    marginBottom: verticalScale(10),
    width: '100%',
    justifyContent: 'center',
    shadowColor: '#3A8A10',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  pauseBtnSecondary: {
    backgroundColor: 'rgba(245,242,235,0.95)',
    shadowColor: 'rgba(0,0,0,0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 2,
  },
  pauseBtnText: {
    fontSize: moderateScale(16),
    fontWeight: '800' as const,
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  pauseBtnTextSecondary: {
    fontSize: moderateScale(16),
    fontWeight: '800' as const,
    color: '#1A1A2E',
    letterSpacing: 1,
  },
  levelUpOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 95,
  },
  levelUpCard: {
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderRadius: scale(22),
    paddingHorizontal: scale(38),
    paddingVertical: verticalScale(22),
    alignItems: 'center',
    borderWidth: 2,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 28,
    elevation: 16,
    overflow: 'hidden',
  },
  levelUpGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: scale(24),
  },
  levelUpTitle: {
    fontSize: moderateScale(28),
    fontWeight: '900' as const,
    letterSpacing: 4,
    marginTop: verticalScale(6),
    textShadowColor: 'rgba(0,0,0,0.15)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  levelUpName: {
    fontSize: moderateScale(12),
    fontWeight: '800' as const,
    color: '#1A1A2E',
    opacity: 0.5,
    letterSpacing: 4,
    marginTop: verticalScale(4),
  },
  gameOverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 10, 25, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 300,
  },
  gameOverScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(10),
  },
  gameOverCard: {
    backgroundColor: 'rgba(255,254,248,0.98)',
    borderRadius: MODAL.radius,
    padding: MODAL.padding,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    shadowColor: 'rgba(0,0,0,0.45)',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 1,
    shadowRadius: 48,
    elevation: 24,
    overflow: 'hidden',
  },
  goCardTopAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: scale(4),
    backgroundColor: '#FF5252',
    opacity: 0.85,
  },
  gameOverTitle: {
    fontSize: moderateScale(36),
    fontWeight: '900' as const,
    color: '#FF3030',
    marginTop: verticalScale(8),
    textShadowColor: 'rgba(20,10,10,0.6)',
    textShadowOffset: { width: 1, height: 3 },
    textShadowRadius: 2,
    letterSpacing: 2,
  },
  gameOverSubtitle: {
    fontSize: moderateScale(12),
    fontWeight: '600' as const,
    color: '#1A1A2E',
    opacity: 0.45,
    marginTop: verticalScale(2),
    marginBottom: verticalScale(14),
  },
  goStatsRow: {
    flexDirection: 'row',
    gap: scale(8),
    marginBottom: verticalScale(14),
    width: '100%',
  },
  goStatItem: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: scale(16),
    padding: scale(10),
    borderWidth: 1,
    borderColor: 'rgba(26,26,46,0.08)',
    shadowColor: 'rgba(0,0,0,0.06)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 2,
  },
  goStatIcon: {
    width: scale(30),
    height: scale(30),
    borderRadius: scale(10),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(4),
  },
  goStatValue: {
    fontSize: moderateScale(18),
    fontWeight: '900' as const,
    color: '#1A1A2E',
  },
  goStatLabel: {
    fontSize: moderateScale(8),
    fontWeight: '800' as const,
    color: '#A09080',
    letterSpacing: 1,
    marginTop: verticalScale(1),
  },
  goLevelReached: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(7),
    borderRadius: scale(14),
    borderWidth: 1,
    marginBottom: verticalScale(14),
    gap: scale(6),
  },
  goLevelReachedText: {
    fontSize: moderateScale(11),
    fontWeight: '800' as const,
    letterSpacing: 0.5,
  },
  newBadgesSection: {
    width: '100%',
    marginBottom: verticalScale(14),
    alignItems: 'center',
  },
  newBadgesTitle: {
    fontSize: moderateScale(14),
    fontWeight: '800' as const,
    color: '#D4920B',
    marginBottom: verticalScale(8),
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(8),
    justifyContent: 'center',
  },
  badgeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(6),
    borderRadius: scale(14),
    gap: scale(4),
  },
  badgeIcon: {
    fontSize: moderateScale(14),
  },
  badgeName: {
    fontSize: moderateScale(10),
    fontWeight: '800' as const,
  },
  goButtons: {
    width: '100%',
    gap: verticalScale(8),
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#55B020',
    paddingVertical: verticalScale(16),
    borderRadius: scale(16),
    gap: scale(10),
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#2A7A00',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 10,
  },
  retryButtonHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: 'rgba(180,240,120,0.35)',
    borderTopLeftRadius: scale(20),
    borderTopRightRadius: scale(20),
  },
  retryText: {
    fontSize: moderateScale(18),
    fontWeight: '900' as const,
    color: '#FFFFFF',
    letterSpacing: 3,
    textShadowColor: 'rgba(10,40,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 2,
  },
  homeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245,242,235,0.95)',
    paddingVertical: verticalScale(14),
    borderRadius: scale(14),
    gap: scale(8),
    borderWidth: 0,
    shadowColor: 'rgba(0,0,0,0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 2,
  },
  homeText: {
    fontSize: moderateScale(14),
    fontWeight: '800' as const,
    color: '#1A1A2E',
  },
  hudRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
  },
  hudMusicBtn: {
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(8),
    borderRadius: scale(20),
  },
  goBottomRow: {
    flexDirection: 'row',
    gap: scale(8),
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4A8FCC',
    paddingVertical: verticalScale(14),
    paddingHorizontal: scale(24),
    borderRadius: scale(14),
    gap: scale(8),
    borderWidth: 0,
    shadowColor: '#2A6FAA',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 4,
  },
  shareText: {
    fontSize: moderateScale(14),
    fontWeight: '800' as const,
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  gothamMoonGlow: {
    position: 'absolute',
    top: verticalScale(15),
    right: scale(35),
    width: scale(80),
    height: scale(80),
    borderRadius: scale(40),
    backgroundColor: '#FFD84A',
    opacity: 0.12,
  },
  gothamMoon: {
    position: 'absolute',
    top: verticalScale(25),
    right: scale(46),
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: '#FFFAE0',
    opacity: 0.75,
    shadowColor: '#FFD84A',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  neonZoneOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 5,
    opacity: 0.12,
  },
  neonZoneTop: {
    position: 'absolute',
    top: verticalScale(60),
    alignSelf: 'center',
  },
  neonZoneBottom: {
    position: 'absolute',
    bottom: GROUND_HEIGHT + verticalScale(20),
    alignSelf: 'center',
  },
  neonZoneMiddleRow: {
    position: 'absolute',
    top: '40%',
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(12),
  },
  neonZoneSide: {
    width: scale(36),
    alignItems: 'center',
  },
  neonZoneCenter: {
    flex: 1,
    alignItems: 'center',
  },
  neonZoneLabel: {
    alignItems: 'center',
  },
  neonZoneLabelText: {
    fontSize: moderateScale(11),
    fontWeight: '800' as const,
    letterSpacing: 1,
  },
  trickLabelOverlay: {
    position: 'absolute',
    top: '30%',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 85,
  },
  trickLabelCard: {
    backgroundColor: 'rgba(8,8,22,0.82)',
    paddingHorizontal: scale(22),
    paddingVertical: verticalScale(9),
    borderRadius: scale(18),
    borderWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 20,
    elevation: 10,
  },
  trickLabelText: {
    fontSize: moderateScale(24),
    fontWeight: '900' as const,
    letterSpacing: 4,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  comboOverlay: {
    position: 'absolute',
    top: '22%',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 86,
  },
  comboBadge: {
    backgroundColor: 'rgba(255,224,0,0.15)',
    borderWidth: 1.5,
    borderColor: '#FFE000',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(5),
    borderRadius: scale(14),
  },
  comboText: {
    fontSize: moderateScale(14),
    fontWeight: '900' as const,
    color: '#FFE000',
    letterSpacing: 2,
  },
  readyTrickHints: {
    marginTop: verticalScale(10),
    alignItems: 'center',
    gap: verticalScale(3),
  },
  readyHintLine: {
    fontSize: moderateScale(10),
    fontWeight: '700' as const,
    color: 'rgba(255,255,255,0.55)',
    letterSpacing: 0.5,
  },
  readyHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  neonZoneLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  coinsEarnedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF9EE',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(8),
    borderRadius: scale(14),
    borderWidth: 1.5,
    borderColor: 'rgba(232,200,112,0.6)',
    marginBottom: verticalScale(14),
    gap: scale(6),
  },
  coinsEarnedText: {
    fontSize: moderateScale(18),
    fontWeight: '900' as const,
    color: '#D4920B',
  },
  coinsEarnedLabel: {
    fontSize: moderateScale(11),
    fontWeight: '700' as const,
    color: '#A08040',
  },
});

  effectPickup: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
  },
  effectPickupOrb: {
    borderRadius: scale(14),
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  effectPickupIcon: {
    fontSize: moderateScale(12),
  },
  effectPickupGlow: {
    position: 'absolute',
    borderRadius: scale(20),
  },
  effectIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 99,
  },
  effectIndicatorPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(5),
    borderRadius: scale(14),
    borderWidth: 1.5,
    gap: scale(5),
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  effectIndicatorIcon: {
    fontSize: moderateScale(13),
  },
  effectIndicatorName: {
    fontSize: moderateScale(11),
    fontWeight: '900' as const,
    letterSpacing: 1.5,
  },
  effectTimerBar: {
    height: verticalScale(3),
    borderRadius: verticalScale(1.5),
    marginTop: verticalScale(2),
  },
  effectActivateOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 88,
  },
  effectActivateCard: {
    paddingHorizontal: scale(28),
    paddingVertical: verticalScale(12),
    borderRadius: scale(20),
    borderWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  effectActivateIcon: {
    fontSize: moderateScale(22),
  },
  effectActivateText: {
    fontSize: moderateScale(22),
    fontWeight: '900' as const,
    letterSpacing: 3,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  blobEffectRing: {
    position: 'absolute',
    borderRadius: 999,
    borderWidth: 2,
  },
  blobEffectTrail: {
    position: 'absolute',
    borderRadius: scale(4),
  },
});

export const trickIconStyles = StyleSheet.create({
  iconWrap: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(10),
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
