import { SCREEN, scale } from './layout';

const gapScale = SCREEN.height / 844;

export const GAME_CONFIG = {
  GRAVITY: 0.34,
  JUMP_FORCE: -6.8,
  OBSTACLE_SPEED: 3.15,
  OBSTACLE_GAP: Math.round(140 * gapScale),
  OBSTACLE_WIDTH: Math.round(scale(58)),
  OBSTACLE_SPAWN_INTERVAL: 1250,
  SPEED_INCREMENT: 0.00015,
  TAP_SPEED_BOOST: 0.056,
  TAP_SPEED_DECAY: 0.989,
  MAX_TAP_SPEED_BONUS: 0.75,
  MAX_SPEED_MULTIPLIER: 5.0,
  POLE_PASS_SPEED_KICK: 0.040,
  POLE_SPEED_DECAY: 0.993,
  MAX_POLE_SPEED_BONUS: 0.55,
  CHARACTER_SIZE: Math.round(SCREEN.width * 0.13),
  HITBOX_SHRINK: 0.66,
  CHARACTER_X_POSITION: 0.22,
  CLOUD_COUNT: 5,
  FRAME_RATE: 16,
  VELOCITY_DAMPING: 0.990,
  MAX_FALL_VELOCITY: 4.2,
  FALL_DRAG: 0.955,
  PHASE_SWITCH_INTERVAL: 6,
  SLOW_SPEED_MULT: 0.5,
  FAST_SPEED_MULT: 1.05,
  SLOW_GRAVITY: 0.28,
  FAST_GRAVITY: 0.42,
  SLOW_JUMP: -6.2,
  FAST_JUMP: -7.8,
  SLOW_GAP: Math.round(166 * gapScale),
  FAST_GAP: Math.round(130 * gapScale),
  PHASE_TRANSITION_FRAMES: 35,
  FIRST_PHASE_THRESHOLD: 2,
  CALM_LOCK_THRESHOLD: 3,
  CALM_DURATION: 3,
  CRUISE_BOB_AMPLITUDE: 0.72,
  CRUISE_BOB_SPEED: 0.062,
  CRUISE_MOMENTUM: 0.048,
  CRUISE_MOMENTUM_DECAY: 0.992,
  CRUISE_GRAVITY_SOFTEN: 0.82,
  CRUISE_TAP_SOFTNESS: 0.88,
  CRUISE_IDLE_DRIFT: 0.018,
  CRUISE_DRIFT_DECAY: 0.985,
  CRUISE_POST_TAP_GLIDE: 0.94,
  SQUEEZE_HITBOX_SHRINK: 0.52,
  SQUEEZE_PROXIMITY: 2.5,
  SQUEEZE_VISUAL_COMPRESS: 0.058,
  SQUEEZE_VISUAL_STRETCH: 0.045,
  SQUEEZE_APPROACH_TENSE: 0.022,
  SQUEEZE_EXIT_RELEASE: 0.035,
  AIRFLOW_DURATION: 40,
  AIRFLOW_STREAK_COUNT: 6,
  AIRFLOW_LINEAR_STRENGTH: 0.88,
  AIRFLOW_WOBBLE_REDUCE: 0.65,
  AIRFLOW_GLIDE_BOOST: 0.035,
  AIRFLOW_STREAMLINE_FACTOR: 0.05,
  HIGH_SPEED_FORGIVENESS_START: 1.2,
  HIGH_SPEED_FORGIVENESS_MAX: 2.5,
  HIGH_SPEED_HITBOX_SHRINK_BONUS: 0.10,
  HIGH_SPEED_EDGE_GRACE: 4.0,
  HIGH_SPEED_EDGE_GRACE_MAX: 9.5,
  IN_GAP_ASSIST_RANGE: 2.0,
  IN_GAP_GRAVITY_DAMPEN: 0.62,
  IN_GAP_WOBBLE_DAMPEN: 0.58,
  IN_GAP_CENTERING_FORCE: 0.18,
  SQUEEZE_FORGIVENESS_VISUAL_THRESHOLD: 0.25,
  SQUEEZE_FORGIVE_SPEED_SCALE: 0.35,
  SQUEEZE_FORGIVE_MAX_GRACE: 5.0,
  IN_GAP_SPEED_CENTERING_BOOST: 0.09,
  IN_GAP_LINEAR_DAMPEN: 0.84,
  BLOB_CRUISE_WIDEN: 0.032,
  BLOB_SPEED_STREAMLINE: 0.024,
  BLOB_CALM_ROUND: 0.020,
  BLOB_TAP_WOBBLE_WIDEN: 0.035,
  BLOB_FALL_STRETCH: 0.025,
  BLOB_RISE_COMPRESS: 0.018,
  BLOB_AIRFLOW_NARROW: 0.030,
  BLOB_SQUEEZE_TUCK: 0.040,
  BOTTOM_POLE_HARD_LIMIT: 0,

  APEX_FLOAT_THRESHOLD: 0.8,
  APEX_FLOAT_GRAVITY_MULT: 0.38,
  APEX_FLOAT_DURATION: 8,
  APEX_FLOAT_STRETCH_X: 0.025,
  APEX_FLOAT_STRETCH_Y: 0.018,

  SOFT_BOUNDARY_RANGE: 45,
  SOFT_BOUNDARY_FORCE: 0.35,
  SOFT_BOUNDARY_DAMPEN: 0.88,

  TAP_RHYTHM_WINDOW: 80,
  TAP_RHYTHM_SMOOTH_BONUS: 0.15,
  TAP_RHYTHM_DECAY: 0.985,
  TAP_RHYTHM_VELOCITY_SMOOTH: 0.92,

  WAKE_DRIFT_DURATION: 22,
  WAKE_DRIFT_LIFT: 0.12,
  WAKE_DRIFT_STREAMLINE: 0.04,

  APPROACH_LEAN_RANGE: 3.5,
  APPROACH_LEAN_FORCE: 0.06,
  APPROACH_LEAN_DAMPEN: 0.94,

  MOMENTUM_CHAIN_DECAY: 0.988,
  MOMENTUM_CHAIN_MAX: 1.0,
  MOMENTUM_CHAIN_GRAVITY_EASE: 0.06,
  MOMENTUM_CHAIN_RISE_BOOST: 0.04,

  SWOOP_RECOVERY_THRESHOLD: 3.5,
  SWOOP_RECOVERY_FORCE: 0.08,
  SWOOP_RECOVERY_DURATION: 16,
};

export interface LevelConfig {
  level: number;
  name: string;
  scoreThreshold: number;
  slowGravity: number;
  fastGravity: number;
  slowJump: number;
  fastJump: number;
  slowGap: number;
  fastGap: number;
  slowSpeedMult: number;
  fastSpeedMult: number;
  spawnInterval: number;
  phaseInterval: number;
  color: string;
}

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    name: 'CHILL',
    scoreThreshold: 0,
    slowGravity: 0.24,
    fastGravity: 0.34,
    slowJump: -6.1,
    fastJump: -7.3,
    slowGap: 160,
    fastGap: 164,
    slowSpeedMult: 0.55,
    fastSpeedMult: 0.88,
    spawnInterval: 1380,
    phaseInterval: 5,
    color: '#7EC850',
  },
  {
    level: 2,
    name: 'CRUISE',
    scoreThreshold: 5,
    slowGravity: 0.28,
    fastGravity: 0.38,
    slowJump: -6.4,
    fastJump: -7.6,
    slowGap: 152,
    fastGap: 156,
    slowSpeedMult: 0.60,
    fastSpeedMult: 0.96,
    spawnInterval: 1290,
    phaseInterval: 5,
    color: '#5B9BD5',
  },
  {
    level: 3,
    name: 'FLOW',
    scoreThreshold: 10,
    slowGravity: 0.33,
    fastGravity: 0.43,
    slowJump: -6.6,
    fastJump: -8.0,
    slowGap: 140,
    fastGap: 148,
    slowSpeedMult: 0.65,
    fastSpeedMult: 1.02,
    spawnInterval: 1210,
    phaseInterval: 5,
    color: '#FFD84A',
  },
  {
    level: 4,
    name: 'TURBO',
    scoreThreshold: 16,
    slowGravity: 0.37,
    fastGravity: 0.49,
    slowJump: -6.8,
    fastJump: -8.3,
    slowGap: 130,
    fastGap: 138,
    slowSpeedMult: 0.70,
    fastSpeedMult: 1.08,
    spawnInterval: 1130,
    phaseInterval: 6,
    color: '#FFA94D',
  },
  {
    level: 5,
    name: 'BEAST',
    scoreThreshold: 24,
    slowGravity: 0.40,
    fastGravity: 0.53,
    slowJump: -7.0,
    fastJump: -8.7,
    slowGap: 123,
    fastGap: 130,
    slowSpeedMult: 0.75,
    fastSpeedMult: 1.15,
    spawnInterval: 1060,
    phaseInterval: 6,
    color: '#FF6B6B',
  },
  {
    level: 6,
    name: 'INSANE',
    scoreThreshold: 35,
    slowGravity: 0.43,
    fastGravity: 0.57,
    slowJump: -7.3,
    fastJump: -9.2,
    slowGap: 116,
    fastGap: 123,
    slowSpeedMult: 0.80,
    fastSpeedMult: 1.23,
    spawnInterval: 990,
    phaseInterval: 7,
    color: '#B57EDC',
  },
  {
    level: 7,
    name: 'DEMON',
    scoreThreshold: 50,
    slowGravity: 0.46,
    fastGravity: 0.62,
    slowJump: -7.6,
    fastJump: -9.6,
    slowGap: 110,
    fastGap: 118,
    slowSpeedMult: 0.85,
    fastSpeedMult: 1.32,
    spawnInterval: 910,
    phaseInterval: 7,
    color: '#E8453C',
  },
];

export const OBSTACLE_TUNING = {
  GAP_CENTER_MIN_PADDING: 75,
  GAP_CENTER_MAX_PADDING: 45,
  PIPE_WIDTH: 58,
  PIPE_CAP_HEIGHT: 18,
  HITBOX_INSET_X: 2,
  HITBOX_INSET_Y: 0,
  PLAYER_FORGIVENESS: 4,
} as const;

export const BLOCK_COLORS = [
  '#FF6B8A',
  '#2DD4A8',
  '#FFB347',
  '#C06CF0',
  '#A8E847',
  '#5BC8F5',
];

export const BLOCK_COLOR_PAIRS: [string, string][] = [
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
];
