import { SCREEN, scale } from './layout';

const gapScale = SCREEN.height / 844;

export const GAME_CONFIG = {
  GRAVITY: 0.32,
  JUMP_FORCE: -6.8,
  OBSTACLE_SPEED: 2.65,
  OBSTACLE_GAP: Math.round(155 * gapScale),
  OBSTACLE_WIDTH: Math.round(scale(58)),
  OBSTACLE_SPAWN_INTERVAL: 1450,
  SPEED_INCREMENT: 0.00010,
  TAP_SPEED_BOOST: 0.038,
  TAP_SPEED_DECAY: 0.985,
  MAX_TAP_SPEED_BONUS: 0.45,
  MAX_SPEED_MULTIPLIER: 3.2,
  POLE_PASS_SPEED_KICK: 0.025,
  POLE_SPEED_DECAY: 0.990,
  MAX_POLE_SPEED_BONUS: 0.35,
  CHARACTER_SIZE: Math.round(SCREEN.width * 0.13),
  HITBOX_SHRINK: 0.78,
  CHARACTER_X_POSITION: 0.22,
  CLOUD_COUNT: 5,
  FRAME_RATE: 16,
  VELOCITY_DAMPING: 0.993,
  MAX_FALL_VELOCITY: 3.8,
  FALL_DRAG: 0.955,
  PHASE_SWITCH_INTERVAL: 6,
  SLOW_SPEED_MULT: 0.45,
  FAST_SPEED_MULT: 0.90,
  SLOW_GRAVITY: 0.24,
  FAST_GRAVITY: 0.36,
  SLOW_JUMP: -5.8,
  FAST_JUMP: -7.0,
  SLOW_GAP: Math.round(175 * gapScale),
  FAST_GAP: Math.round(148 * gapScale),
  PHASE_TRANSITION_FRAMES: 35,
  FIRST_PHASE_THRESHOLD: 2,
  CALM_LOCK_THRESHOLD: 3,
  CALM_DURATION: 3,
  CRUISE_BOB_AMPLITUDE: 0.30,
  CRUISE_BOB_SPEED: 0.04,
  SQUEEZE_HITBOX_SHRINK: 0.72,
  SQUEEZE_PROXIMITY: 1.8,
  AIRFLOW_DURATION: 24,
  AIRFLOW_STREAK_COUNT: 3,
  HIGH_SPEED_FORGIVENESS_START: 1.1,
  HIGH_SPEED_FORGIVENESS_MAX: 2.0,
  HIGH_SPEED_HITBOX_SHRINK_BONUS: 0.03,
  HIGH_SPEED_EDGE_GRACE: 1.5,
  HIGH_SPEED_EDGE_GRACE_MAX: 3.0,
  IN_GAP_ASSIST_RANGE: 1.7,
  IN_GAP_GRAVITY_DAMPEN: 0.70,
  IN_GAP_WOBBLE_DAMPEN: 0.65,
  IN_GAP_CENTERING_FORCE: 0.16,
  SQUEEZE_FORGIVENESS_VISUAL_THRESHOLD: 0.15,
  SQUEEZE_FORGIVE_SPEED_SCALE: 0.10,
  SQUEEZE_FORGIVE_MAX_GRACE: 1.5,
  IN_GAP_SPEED_CENTERING_BOOST: 0.10,
  IN_GAP_LINEAR_DAMPEN: 0.91,
  BLOB_CRUISE_WIDEN: 0.025,
  BLOB_SPEED_STREAMLINE: 0.018,
  BLOB_CALM_ROUND: 0.015,
  BLOB_TAP_WOBBLE_WIDEN: 0.03,
  BLOB_FALL_STRETCH: 0.02,
  BLOB_RISE_COMPRESS: 0.015,
  BOTTOM_POLE_HARD_LIMIT: 0,
};

export interface LevelConfig {
  level: number;
  name: string;
  scoreThreshold: number;
  slowGravity: number;
  fastGravity: number;
  slowJump: number;
  fastJump: number;
  slowGap: number;
  fastGap: number;
  slowSpeedMult: number;
  fastSpeedMult: number;
  spawnInterval: number;
  phaseInterval: number;
  color: string;
}

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    name: 'CHILL',
    scoreThreshold: 0,
    slowGravity: 0.20,
    fastGravity: 0.28,
    slowJump: -5.6,
    fastJump: -6.5,
    slowGap: 176,
    fastGap: 180,
    slowSpeedMult: 0.48,
    fastSpeedMult: 0.75,
    spawnInterval: 1600,
    phaseInterval: 6,
    color: '#7EC850',
  },
  {
    level: 2,
    name: 'CRUISE',
    scoreThreshold: 6,
    slowGravity: 0.24,
    fastGravity: 0.32,
    slowJump: -5.9,
    fastJump: -6.9,
    slowGap: 168,
    fastGap: 172,
    slowSpeedMult: 0.52,
    fastSpeedMult: 0.82,
    spawnInterval: 1500,
    phaseInterval: 6,
    color: '#5B9BD5',
  },
  {
    level: 3,
    name: 'FLOW',
    scoreThreshold: 12,
    slowGravity: 0.28,
    fastGravity: 0.36,
    slowJump: -6.2,
    fastJump: -7.3,
    slowGap: 158,
    fastGap: 164,
    slowSpeedMult: 0.56,
    fastSpeedMult: 0.88,
    spawnInterval: 1400,
    phaseInterval: 5,
    color: '#FFD84A',
  },
  {
    level: 4,
    name: 'TURBO',
    scoreThreshold: 20,
    slowGravity: 0.32,
    fastGravity: 0.41,
    slowJump: -6.4,
    fastJump: -7.6,
    slowGap: 148,
    fastGap: 154,
    slowSpeedMult: 0.60,
    fastSpeedMult: 0.94,
    spawnInterval: 1300,
    phaseInterval: 6,
    color: '#FFA94D',
  },
  {
    level: 5,
    name: 'BEAST',
    scoreThreshold: 30,
    slowGravity: 0.35,
    fastGravity: 0.45,
    slowJump: -6.6,
    fastJump: -7.9,
    slowGap: 140,
    fastGap: 146,
    slowSpeedMult: 0.65,
    fastSpeedMult: 1.00,
    spawnInterval: 1200,
    phaseInterval: 6,
    color: '#FF6B6B',
  },
  {
    level: 6,
    name: 'INSANE',
    scoreThreshold: 42,
    slowGravity: 0.38,
    fastGravity: 0.48,
    slowJump: -6.8,
    fastJump: -8.2,
    slowGap: 132,
    fastGap: 138,
    slowSpeedMult: 0.70,
    fastSpeedMult: 1.06,
    spawnInterval: 1120,
    phaseInterval: 7,
    color: '#B57EDC',
  },
  {
    level: 7,
    name: 'DEMON',
    scoreThreshold: 58,
    slowGravity: 0.41,
    fastGravity: 0.52,
    slowJump: -7.0,
    fastJump: -8.5,
    slowGap: 125,
    fastGap: 132,
    slowSpeedMult: 0.75,
    fastSpeedMult: 1.14,
    spawnInterval: 1040,
    phaseInterval: 7,
    color: '#E8453C',
  },
];

export const OBSTACLE_TUNING = {
  GAP_CENTER_MIN_PADDING: 75,
  GAP_CENTER_MAX_PADDING: 45,
  PIPE_WIDTH: 58,
  PIPE_CAP_HEIGHT: 18,
  HITBOX_INSET_X: 2,
  HITBOX_INSET_Y: 0,
  PLAYER_FORGIVENESS: 4,
} as const;

export const BLOCK_COLORS = [
  '#FF6B8A',
  '#2DD4A8',
  '#FFB347',
  '#C06CF0',
  '#A8E847',
  '#5BC8F5',
];

export const BLOCK_COLOR_PAIRS: [string, string][] = [
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
  ['#73BF2E', '#5A9A24'],
];
